version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
      - "443"

  client: 
    ports:
      - "3000:3000"

  sonet_sql:
    container_name: sonet_sql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=test@123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1401:1433"
