export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PROFILE_ROUTE = '/profile'
export const FRIEND_ROUTE = '/friends'
export const MESSAGE_ROUTE = '/message'
export const STRANGE_ROUTE = '/strange'
export const CONTROL_ROUTE = '/control'